### PR TITLE
feat: support custom fonts

### PR DESCRIPTION
**Pull request by rgodha24**
I added custom fonts support

it supports any latin fonts from [fontsource](https://fontsource.org/). 

because radix-themes doesn't have a [combobox](https://ui.shadcn.com/docs/components/combobox), it's just in a giant \<Select\>. You can just type in the name of the font from fontsource and it searches through the select for you.
we could change it to use this [ariakit example](https://ariakit.org/examples/combobox-radix-select), but that's another dep and I wasn't sure if you'd be fine with that.

### CODE REVIEW

**Review by QuiiBz — CHANGES_REQUESTED** [review]
Thanks for the PR! I'm not quite sure to understand what "Installed fonts" mean, you could provide more details?

We'll need some virtualized list too, opening the font dropdown is currently freezing the tab for ~500ms on a high-end MacBook:
Screenshot 2024-08-28 at 13 52 26

We should also consider lazy-loading the fonts files themselves, instead of triggering +1500 requests to jsdelivr when opening the dropdown.

Typecheck, eslint and some tests are failing, could you take a look at those?

**Comment by rgodha24** [comment]
Yeah so the way I implemented it is that the installed fonts were *supposed* to be the only ones loaded from the cdn. I completely forgot that virtualization was needed, and was too lazy to check why my computer lagged out while running it. 

I think the theoretically correct UI for this would look like this, where the "+" button opens a searchbox with maybe just 5 entries.
image

I'll update the ui and fix the tests/typechecking after this class :)

**Comment by rgodha24** [comment]
https://github.com/user-attachments/assets/11db48e1-3a6d-4fb4-bc77-be3a514cbfd2

this seems better lol

**Comment by rgodha24** [comment]
I kinda hate being that guy, but the CI is working on my machine. I have no clue why its failing on GH actions. I even did a fresh install of my node_modules with the pnpm store cleaned.

**Comment by QuiiBz** [comment]
> I kinda hate being that guy, but the CI is working on my machine. I have no clue why its failing on GH actions. I even did a fresh install of my node_modules with the pnpm store cleaned.

Had the same issue on my two PRs this morning, so it's not you. It was working fine 3 months ago so not sure what's going on yet, will take a look.

**Comment by QuiiBz** [comment]
Fixed the issues in https://github.com/QuiiBz/ogstudio/pull/100, you can rebase

**Comment by rgodha24** [comment]
git is hard but I think it should be good now

**Review by QuiiBz — APPROVED** [review]
Pushed a few refactors & design tweaks (less gap, "pre-installed" tag for default fonts):

Screenshot 2024-09-01 at 08 21 52

Thanks a lot for this PR!

**Pull request merged**
